website/blog/urls.py
from django.urls import path, re_path

from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('post/', views.PostListView.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)$', views.PostDetailView.as_view(), name='post_detail'),
    path('archive/', views.PostArchiveView.as_view(), name='post_archive'),
    path('archive/<int:year>', views.PostYearArchiveView.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>', views.PostMonthArchiveView.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDayArchiveView.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTodayArchiveView.as_view(), name='post_today_archive'),
    # tag 관련 추가
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    # search 관련 추가
    path('search/', views.SearchFormView.as_view(), name='search')
]

website/board/urls.py
from django.urls import path, re_path

from board import views

app_name = 'board'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('post/', views.PostListView.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)$', views.PostDetailView.as_view(), name='post_detail'),
    # tag 관련 추가
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    # search 관련 추가
    path('search/', views.SearchFormView.as_view(), name='search')
]

website/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    # Admin 사이트
    path('admin/', admin.site.urls),
    
    # 계정 관리
    # https://github.com/django/django/blob/master/django/contrib/auth/urls.py
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'), 
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    # 어플리케이션
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('board/', include('board.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/board/models.py
from django.db import models
from django.urls import reverse
from taggit.managers import TaggableManager


class Post(models.Model):
    title = models.CharField(verbose_name='TITLE', max_length=50)
    slug = models.SlugField('SLUG', unique=True, allow_unicode=True, help_text='one word for title alias')
    description = models.CharField('DESCRIPTION', max_length= 100, blank= True, help_text='simple description text' )
    content = models.TextField('CONTENT')
    create_dt = models.DateTimeField('CREATE DATE', auto_now_add=True)
    modify_dt = models.DateTimeField('MODIFY DATE', auto_now=True)
    tags = TaggableManager(blank=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'blog_posts'
        ordering = ('-modify_dt',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('board:post_detail', args=(self.slug,))

    def get_previous(self):
        return self.get_previous_by_modify_dt()

    def get_next(self):
        return self.get_next_by_modify_dt()

website/board/forms.py
from django import forms

class PostSearchForm(forms.Form):
    search_word = forms.CharField(label='Search Word')

website/board/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import ListView, DetailView, TemplateView, FormView
from django.views.generic.dates import ArchiveIndexView, YearArchiveView, MonthArchiveView
from django.views.generic.dates import DayArchiveView,TodayArchiveView

from board.models import Post

# 댓글
from django.conf import settings

# search
from board.forms import PostSearchForm
from django.db.models import Q
from django.shortcuts import render

class PostListView(ListView):
    model = Post
    template_name = 'board/post_all.html'
    context_object_name = 'posts'
    paginate_by = 2

class PostDetailView(DetailView):
    model = Post

    # 댓글
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['disqus_short'] = f"{settings.DISQUS_SHORTNAME}"
        context['disqus_id'] = f"post-{self.object.id}-{self.object.slug}"
        context['disqus_url'] = f"{settings.DISQUS_MY_DOMAIN}{self.object.get_absolute_url()}"
        context['disqus_title'] = f"{self.object.slug}"
        return context

class PostArchiveView(ArchiveIndexView):
    model = Post
    date_field = 'modify_dt'

class PostYearArchiveView(YearArchiveView) :
    model = Post
    date_field = 'modify_dt'

class PostMonthArchiveView(MonthArchiveView):
    model = Post
    date_field = 'modify_dt'

class PostDayArchiveView(DayArchiveView):
    model = Post
    date_field = 'modify_dt'

class PostTodayArchiveView(TodayArchiveView):
    model = Post
    date_field = 'modify_dt'

#Tag View
class TagCloudTV(TemplateView):
    template_name = 'taggit/taggit_cloud.html'

class TaggedObjectLV(ListView):
    template_name = 'taggit/taggit_post_list.html'
    model= Post

    def get_queryset(self):
        return Post.objects.filter(tags__name=self.kwargs.get('tag'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tagname'] = self.kwargs['tag']
        return context

#Search Form View
class SearchFormView(FormView):
    form_class = PostSearchForm
    template_name = 'board/post_search.html'

    def form_valid(self, form):
        searchWord = form.cleaned_data['search_word']
        post_list = Post.objects.filter(Q(title__icontains=searchWord)
                                        | Q(description__icontains=searchWord)
                                        | Q(content__icontains=searchWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = searchWord
        context['object_list'] = post_list

        #No redirection
        return render(self.request, self.template_name, context)

website/board/templates/board/post_all.html
<!--extends 태그는 첫 줄에 작성-->
{% extends 'base.html' %}
{% load static %}

{% block title %} bookmark_detail.html {% endblock %}

{% block header%}
  <header class="masthead" style="background-image: url('{%static 'img/post-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>블로그</h1>
            <span class="subheading">저의 생각을 기록한 공간입니다</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{%endblock%}


{% block content %}
    <h2>My Blog List</h2>
    <br>
    {% for post in posts %}
        <h3><a href ='{{post.get_absolute_url}}'>{{post.title}} </a></h3>
        {{post.modify_dt|date:"N d, Y"}}
        <p>{{post.description}}</p>
    {% endfor %}
    <br>

    <div>
        <span>
            {% if page_obj.has_previous %}
                <a href="?page={{page_obj.previous_page_number}}">[이전페이지]</a>
            {% endif %}

            전체 {{page_obj.paginator.num_pages}}페이지 중 {{ page_obj.number}} 페이지

             {% if page_obj.has_next %}
                <a href="?page={{page_obj.next_page_number}}">[다음페이지]</a>
            {% endif %}
        </span>
    </div>
</body>
{% endblock %}

website/board/templates/board/post_detail.html
<!--extends 태그는 첫 줄에 작성-->
{% extends 'base.html' %}
{% load static %}

{% block title %} post_detail.html {% endblock %}
{% block extra-style %}
<style>
.post-body {
    width: 80%;
    margin: auto;
    font-family: "Lucida Grande", Verdana, Arial, sans-serif;
    font-size: 16px;
}
</style>
{% endblock extra-style %}

{% block header%}
  <header class="masthead" style="background-image: url('{%static 'img/post-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>블로그</h1>
            <span class="subheading">저의 생각을 기록한 공간입니다</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{%endblock%}



{% block content %}
<div class="post-body">
    <!--제목-->
    <h2>{{object.title}}</h2>
    <!--이전/다음 포스트 이동-->
    <p>
        {% if object.get_previous %}
            <a href="{{ object.get_previous.get_absolute_url }}" title="prev_post">
                &laquo;-- {{ object.get_previous }}
            </a>
        {% endif %}

        {% if object.get_next %}
            <a href="{{ object.get_next.get_absolute_url }}" title="next_post">
                {{ object.get_next }} --&raquo;
            </a>
        {% endif %}
    </p>
    <!-- 수정날짜 -->
    <p> {{object.modify_dt|date:"j F Y"}}</p>
    <br>
    <!-- 본문 -->
    <div>
        {{ object.content|linebreaks }}
    </div>

    <!--Tag 관련 추가-->
    <br>
    <div>
        <b>TAGS</b> <i class="fas fa-tag"></i>
        {% load taggit_templatetags2_tags %}
        {% get_tags_for_object object as "tags" %}
        {% for tag in tags %}
            <a href="{% url 'board:tagged_object_list' tag.name %}">{{tag.name}}</a>
        {% endfor %}
	&emsp;
    </div>

    <!--댓글 관련 추가-->
    <!--https://django-web-programming-2.disqus.com/admin/install/platforms/universalcode/-->
    <br>
    <div id="disqus_thread"></div>
</div>
{% endblock %}

{% block extra-script %}
    <script>

    var disqus_config = function () {
        this.page.url = '{{disqus_url}}';
        this.page.identifier = '{{disqus_id}}';
    };

    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://django-web-programming-2.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
    </script>
    <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
{%endblock%}

website/board/templates/board/post_search.html
<!--extends 태그는 첫 줄에 작성-->
{% extends 'base.html' %}
{% load static %}

{% block title %}post_search.html{% endblock %}

{% block header%}
  <header class="masthead" style="background-image: url('{%static 'img/post-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>블로그</h1>
            <span class="subheading">저의 생각을 기록한 공간입니다</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{%endblock%}

{% block content %}

    <h1>Blog Search</h1>
    <br>

    <form action="." method="post"> {% csrf_token %}
        {{ form.as_table }}
        <input type="submit" value="Submit" class="btn btn-primary btn-sm">
    </form>

    <br/><br/>

    {% if object_list %}
        {% for post in object_list %}
        <h2><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></h2>
        {{ post.modify_dt|date:"N d, Y" }}
        <p>{{ post.description }}</p>
        {% endfor %}

    {% elif search_term %}
    <b><i>Search Word({{ search_term }}) Not Found !</i></b>
    {% endif %}

{% endblock %}