website/blog/urls.py
from django.urls import path, re_path

from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('post/', views.PostListView.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)$', views.PostDetailView.as_view(), name='post_detail'),
    path('archive/', views.PostArchiveView.as_view(), name='post_archive'),
    path('archive/<int:year>', views.PostYearArchiveView.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>', views.PostMonthArchiveView.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDayArchiveView.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTodayArchiveView.as_view(), name='post_today_archive'),
    # tag 관련 추가
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    # search 관련 추가
    path('search/', views.SearchFormView.as_view(), name='search')
]

website/bookmark/urls.py
from django.urls import path
# from bookmark.views import BookmarkLV, BookmarkDV
from bookmark import views


app_name = 'bookmark'
urlpatterns = [
    # 리스트: http://127.0.0.1:8000/bookmark/
    path('', views.BookmarkLV.as_view(), name='index'),

    # 상세페이지: http://127.0.0.1:8000/bookmark/1/
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),

    # 생성: http://127.0.0.1:8000/bookmark/add/
    path('add/', views.BookmarkCreateView.as_view(), name="add",),

    # 수정: http://127.0.0.1:8000/bookmark/1/update/
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name="update",),

    # 삭제: http://127.0.0.1:8000/bookmark/1/delete/
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name="delete",),
]

website/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    # Admin 사이트
    path('admin/', admin.site.urls),
    
    # 계정 관리
    # https://github.com/django/django/blob/master/django/contrib/auth/urls.py
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'), 
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    # 어플리케이션
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('board/', include('board.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/bookmark/models.py
from django.db import models
from django.contrib.auth.models import User


class Bookmark(models.Model):
    title = models.CharField('TITLE', max_length=100, blank=True)
    url = models.URLField('URL', unique=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.title

website/bookmark/views.py
from django.views.generic import ListView, DetailView
from bookmark.models import Bookmark
from django.views.generic import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from mysite.views import OwnerOnlyMixin


class BookmarkLV(ListView):
    model = Bookmark


class BookmarkDV(DetailView):
    model = Bookmark


class BookmarkCreateView(LoginRequiredMixin, CreateView): 
    model = Bookmark 
    fields = ['title', 'url'] 
    success_url = reverse_lazy('bookmark:index') 

    def form_valid(self, form): 
        form.instance.owner = self.request.user 
        return super().form_valid(form)


class BookmarkUpdateView(OwnerOnlyMixin, UpdateView): 
    model = Bookmark 
    fields = ['title', 'url'] 
    success_url = reverse_lazy('bookmark:index') 


class BookmarkDeleteView(OwnerOnlyMixin, DeleteView): 
    model = Bookmark 
    success_url = reverse_lazy('bookmark:index')

website/bookmark/templates/bookmark/bookmark_confirm_delete.html
{% extends "base.html" %}

{% block title %}bookmark_confirm_delete.html{% endblock %}

{% block content %}

    <h1>Bookmark Delete</h1>
    <br>

    <form action="." method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}" ?</p>
        <input type="submit" value="Confirm" class="btn btn-danger btn-sm" />
    </form>

</div>
{% endblock %}

website/bookmark/templates/bookmark/bookmark_detail.html
<!--extends 태그는 첫 줄에 작성-->
{% extends 'base.html' %}
{% load static %}

{% block title %} bookmark_detail.html {% endblock %}

{% block header%}
  <header class="masthead" style="background-image: url('{%static 'img/about-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>북마크 페이지</h1>
            <span class="subheading">제가 자주가는 홈페이지 주소입니다</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{%endblock%}

{% block content %}
    <a href="{% url 'bookmark:update' bookmark.id %}" class="btn btn-primary btn-sm" role="button" aria-pressed="true">수정</a>
    <a href="{% url 'bookmark:delete' bookmark.id %}" class="btn btn-secondary btn-sm" role="button" aria-pressed="true">삭제</a>
    <br>
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <div class="post-preview">
            <h2 class="post-title">
              {{ object.title }}
            </h2>
            <h3 class="post-meta">
                <a href="{{ object.url }}">{{ object.url }}</a>
            </h3>
        </div>
       </div>
   </div>
<br>

{% endblock %}

website/bookmark/templates/bookmark/bookmark_form.html
{% extends "base.html" %}
{% load widget_tweaks %}

{% block title %}bookmark_form.html{% endblock %}

{% block content %}

    <h1>Bookmark Create/Update - {{user}}</h1>
    <p class="font-italic">This is a creation or update form for your bookmark.</p>

    {% if form.errors %}
    <div class="alert alert-danger">
        <div class="font-weight-bold">Wrong! Please correct the error(s) below.</div>
        {{ form.errors }}
    </div>
    {% endif %}

    <form action="." method="post" class="card pt-3">{% csrf_token %}

        <div class="form-group row">
            {{ form.title|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.title|add_class:"form-control"|attr:"autofocus" }}
            </div>
        </div>

        <div class="form-group row">
            {{ form.url|add_label_class:"col-form-label col-sm-2 ml-3 font-weight-bold" }}
            <div class="col-sm-5">
                {{ form.url|add_class:"form-control" }}
            </div>
        </div>

        <div class="form-group">
            <div class="offset-sm-2 col-sm-5">
                <input type="submit" value="Submit" class="btn btn-info"/>
            </div>
        </div>

    </form>

{% endblock %}

website/bookmark/templates/bookmark/bookmark_list.html
<!--extends 태그는 첫 줄에 작성-->
{% extends 'base.html' %}
{% load static %}

{% block title %} bookmark_list.html {% endblock %}

{% block header%}
  <header class="masthead" style="background-image: url('{%static 'img/home-bg.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>북마크 페이지</h1>
            <span class="subheading">제가 자주가는 홈페이지 주소입니다</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{%endblock%}

{% block content %}
    <h2> My Bookmark List</h2>
    <ul>
        <a href="{% url 'bookmark:add'%}" class="btn btn-primary btn-sm float-right" role="button" aria-pressed="true">새로 만들기</a>
        <br><br>
        {% for bookmark in object_list %}
        <li> <a href="{% url 'bookmark:detail' bookmark.id %}">{{ bookmark }}</a> </li>
        {% endfor %}
    </ul>
{% endblock %}