website/blog/urls.py
from django.urls import path, re_path

from blog import views

app_name = 'blog'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('post/', views.PostListView.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)$', views.PostDetailView.as_view(), name='post_detail'),
    path('archive/', views.PostArchiveView.as_view(), name='post_archive'),
    path('archive/<int:year>', views.PostYearArchiveView.as_view(), name='post_year_archive'),
    path('archive/<int:year>/<str:month>', views.PostMonthArchiveView.as_view(), name='post_month_archive'),
    path('archive/<int:year>/<str:month>/<int:day>/', views.PostDayArchiveView.as_view(), name='post_day_archive'),
    path('archive/today/', views.PostTodayArchiveView.as_view(), name='post_today_archive'),
    # tag 관련 추가
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    # search 관련 추가
    path('search/', views.SearchFormView.as_view(), name='search')
]

website/board/urls.py
from django.urls import path, re_path

from board import views

app_name = 'board'
urlpatterns = [
    path('', views.PostListView.as_view(), name='index'),
    path('post/', views.PostListView.as_view(), name='post_list'),
    re_path(r'^post/(?P<slug>[-\w]+)$', views.PostDetailView.as_view(), name='post_detail'),
    # tag 관련 추가
    path('tag/', views.TagCloudTV.as_view(), name='tag_cloud'),
    path('tag/<str:tag>/', views.TaggedObjectLV.as_view(), name='tagged_object_list'),
    # search 관련 추가
    path('search/', views.SearchFormView.as_view(), name='search')
]

website/bookmark/urls.py
from django.urls import path
# from bookmark.views import BookmarkLV, BookmarkDV
from bookmark import views


app_name = 'bookmark'
urlpatterns = [
    # 리스트: http://127.0.0.1:8000/bookmark/
    path('', views.BookmarkLV.as_view(), name='index'),

    # 상세페이지: http://127.0.0.1:8000/bookmark/1/
    path('<int:pk>/', views.BookmarkDV.as_view(), name='detail'),

    # 생성: http://127.0.0.1:8000/bookmark/add/
    path('add/', views.BookmarkCreateView.as_view(), name="add",),

    # 수정: http://127.0.0.1:8000/bookmark/1/update/
    path('<int:pk>/update/', views.BookmarkUpdateView.as_view(), name="update",),

    # 삭제: http://127.0.0.1:8000/bookmark/1/delete/
    path('<int:pk>/delete/', views.BookmarkDeleteView.as_view(), name="delete",),
]

website/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from mysite.views import HomeView, UserCreateView, UserCreateDoneTV


urlpatterns = [
    # Admin 사이트
    path('admin/', admin.site.urls),
    
    # 계정 관리
    # https://github.com/django/django/blob/master/django/contrib/auth/urls.py
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/register/', UserCreateView.as_view(), name='register'), 
    path('accounts/register/done/', UserCreateDoneTV.as_view(), name='register_done'),

    # 어플리케이션
    path('', HomeView.as_view(), name='home'),
    path('bookmark/', include('bookmark.urls')),
    path('board/', include('board.urls')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/templates/base.html
<!--https://startbootstrap.com/themes/clean-blog/-->
<!DOCTYPE html>
<html lang="ko">
{% load static %}
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- title을 block으로 지정해서, 각 템블릿에서 지정가능하도록 설정-->
  <title>{% block title%}base.html{%endblock%} </title>
  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{% static 'vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
  {% block extra-style%} {%endblock%}
</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <!--홈 메뉴 -->
      <a class="navbar-brand" href="{% url 'home'%}">Home</a>
      <!--작은 화면용 메뉴 버튼 -->
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <!--메뉴 시작 -->
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <!-- 메뉴 리스트 -->
        <ul class="navbar-nav ml-auto  nav-pills">
          <!-- 1) BOOKMARK 메뉴 -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'bookmark:index'%}">Bookmark</a>
          </li>
          <!-- 2) BOARD 드롭다운 메뉴 -->
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">Board</a>
            <div class="dropdown-menu">
              <a class="dropdown-item" href="{% url 'board:index' %}">Posts</a>
              <a class="dropdown-item" href="{% url 'board:search' %}">Search</a>
            </div>
          </li>
          <!-- 3) PHOTO 메뉴 -->
          <li class="nav-item">
            <a class="nav-link" href="#">Photo</a>
          </li>
          <!-- 4) Admin 메뉴 -->
          <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index'%}">Admin</a>
          </li>
        </ul>

        <!-- 로그인 메뉴 -->
        <ul class="navbar-nav ml-5 mr-5">
            <li class="nav-item dropdown">
                <!-- [조건1] 로그인한 상태 -->
                {% if user.is_active %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
                    <!-- 로그인한 사용자 이름 디스플레이 -->
            	    <i class="fas fa-user"></i>&ensp;{% firstof user.get_short_name user.get_username %}&ensp;</a>
                <!-- 드롭다운 메뉴 -->
                <div class="dropdown-menu">
            	    <a class="dropdown-item" href="{% url 'logout' %}">로그아웃</a>
            	    <a class="dropdown-item" href="{% url 'password_change' %}">비밀번호 변경</a>
                </div>
                <!-- [조건2] 로그아웃한 상태 -->
                {% else %}
                <a class="nav-link dropdown-toggle text-white" href="#" data-toggle="dropdown">
            	    <i class="fas fa-user"></i>&ensp;로그인 해주세요&ensp;</a>
                <div class="dropdown-menu">
            	    <a class="dropdown-item" href="{% url 'login' %}">로그인</a>
            	    <a class="dropdown-item" href="{% url 'register' %}">회원가입</a>
                </div>
                {% endif %}
            </li>
        </ul>
      </div>
    </div>
  </nav>


 {% block header %} {%endblock%}

<div class="container">
  {% block content %} {%endblock%}
</div>

  <!-- Footer -->
  <footer>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <ul class="list-inline text-center">
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
            <li class="list-inline-item">
              <a href="#">
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              </a>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright &copy; My Website 2020</p>
        </div>
      </div>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %} "></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>


  <!-- Custom scripts for this template -->
  <script src="js/clean-blog.min.js"></script>

{% block extra-script %}{% endblock %}

</body>

</html>

website/templates/home.html
<!--extends 태그는 첫 줄에 작성-->
{% extends 'base.html' %}

<!-- 템플릿 태그를 사용하기 위해서 태그 파일 static을 로딩해야함-->
{% load static %}

<!-- 페이지 타이틀을 home.html이라고 정의-->
{% block title %}home.html{% endblock %}

{% block header%}
  <header class="masthead" style="background-image: url('{%static 'img/copenhagen.jpg' %}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <h1>놀면뭐하니?</h1>
            <span class="subheading">매주 토요일 저녁 7시!</span>
          </div>
        </div>
      </div>
    </div>
  </header>
{%endblock%}

<!--content 영역-->
{% block content %}

<!--수평선 출력-->
    <hr style="margin: 10px 0;">

<!--앱 설명-->
    <div class="row text-center">
        <div class="col-sm-6">
            <h3>What is Lorem Ipsum?</h3>
            <p>Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
        </div>
        <div class="col-sm-6">
            <h3>Why do we use it?</h3>
            <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>
        </div>
    </div>


<!--수평선 출력-->
    <hr style="margin: 10px 0;">
{% endblock content %}